### ISSUE TITLE
Add a workflow to run the validate and test scripts

### ISSUE THREAD

**Issue by danilowoz** [Significa/significa-start#24]

**Comment by pbrandone** [comment]
@danilowoz what do you mean with this? we already have the projects with husky running these validations. Do you mean in the `significa-start` project itself?

**Comment by danilowoz** [comment]
I mean that it would be interesting already have created a Github Actions to run the `validate` and `test` scripts, as it has in husky as well

**Comment by pbrandone** [comment]
I see. makes sense, thanks!
