### ISSUE TITLE
What about options for 'stacks'?

### ISSUE THREAD

**Issue by pedrobslisboa** [Significa/significa-start#35]
It would be nice to have options to choose our stack.

### Problem
Let's suppose the user write the command like this:
```bash
npx @significa/start nextjs hello-world
```
It may be right for some of them since `nextjs` spelling is common and they will receive an Error:
`›   Error: Expected nextjs to be one of: cra, gatsby, next`
So they have to read the documentation to know exactly the stack's name. 

### Solution

With options, we could increase that experience:

![Captura de tela de 2020-07-21 09-17-05](https://user-images.githubusercontent.com/35539594/88053942-f9532300-cb32-11ea-85b2-0bd89dbe1dea.png)
![Captura de tela de 2020-07-21 09-07-03](https://user-images.githubusercontent.com/35539594/88053037-91e8a380-cb31-11ea-9f44-b622cf9482a4.png)

Giving options, we also delivered to users new future stacks without the necessity to be up to date with the documentation. If some stack exists on options you can you, if don't you can't.

----

What do you guys think about it? :thinking:

**Comment by pbrandone** [comment]
Closed by #37
