### ISSUE TITLE
Improve way how it handles the SVG files

### ISSUE THREAD

**Issue by danilowoz** [Significa/significa-start#39]
Currently, there is only one way to import SVGs, which converts to a React Component. We've faced some issues while trying to import as path, like a regular file. So the idea here is to improve how we handle and make sure that all kind of assets is working fine:

For SVGS files: https://www.npmjs.com/package/@svgr/webpack
```jsx
import starUrl, { ReactComponent as Star } from './star.svg'
const App = () => (
  <div>
    <img src={starUrl} alt="star" />
    <Star />
  </div>
)
``` 

For images:
https://www.npmjs.com/package/next-images#usage

**Comment by sastromo** [comment]
done!
