### ISSUE TITLE
Folders structures problem

### ISSUE THREAD

**Issue by pedrobslisboa** [significa/significa-start#46]
## Problem

For some reason every time I try to execute this CLI, the folders structures are messed up, it occurs with all the stacks :/

![Captura de tela de 2020-08-12 10-21-50](https://user-images.githubusercontent.com/35539594/90020054-ada11e80-dc85-11ea-87b9-a30057ce8964.png)

**Comment by pbrandone** [comment]
yeah this is wrong. I'll see what happened. thanks

**Comment by Cleysonlb** [comment]
@pedrobslisboa @pbrandone what would be the right structure?
Common inside `gatsby` path?

**Comment by pbrandone** [comment]
@pedrobslisboa is this still happening? I have been using the CLI and everything seems ok
